# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 26, 23, 14, 29, 23138, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
