# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
