# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 00:27
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160127_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.TextField(default=datetime.datetime(2016, 1, 27, 0, 27, 16, 549659, tzinfo=utc), verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
